_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_400e.yml',
  '_base_/yolov6mt_efficientrep.yml',
  '_base_/yolov6mt_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/yolov6mt_s_400e_coco/model_final

TrainReader:
  batch_size: 8
