_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov6_cspbep.yml',
  '_base_/yolov6_reader_high_aug.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 20
snapshot_epoch: 10
weights: output/yolov6_l_300e_coco/model_final


use_distill: True

CSPBepBackbone:
  csp_e: 0.50

CSPRepPAN:
  csp_e: 0.50

EffiDeHead:
  reg_max: 16
  use_dfl: True
  iou_type: 'giou'
  distill_weight: {class: 1.0, dfl: 1.0} # 1:1


TrainReader:
  batch_size: 32 # total batch_size = 32 * gpu_num

EvalReader:
  batch_size: 4
