_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/yolov7_elannet.yml',
  '_base_/yolov7_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7_l_300e_coco/model_final
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/convnext_tiny_22k_224.pdparams

arch: 'L'

YOLOv5: # YOLOv7 is based on YOLOv5
  backbone: ConvNeXt
  neck: ELANFPN
  yolo_head: YOLOv7Head
  post_process: ~

ConvNeXt:
  arch: 'tiny'
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  return_idx: [1, 2, 3]


TrainReader:
  batch_size: 16


epoch: 36
LearningRate:
  base_lr: 0.0002
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [36]
    use_warmup: false

OptimizerBuilder:
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0005
